In [1]:
import sys
import os
sys.path.append(os.path.abspath(".."))

In [2]:
import numpy as np
SEED = 45
np.random.seed(SEED)

from scipy.optimize import linear_sum_assignment
from sklearn.metrics import mean_squared_error
from models import GibbsSamplerLLFM
from evals import latent_features
from data import generate_synthetic


In [3]:
Y, Z_true, W_true, b_true, p_true = generate_synthetic(T=500, S=4, K_true=2, alpha=2.0, bias=-3, weights=5.0)
#print("Generated synthetic data Y:", Y)
print("Latent probabilities:", p_true)
print("True weight matrix W_true:", W_true)
print("True bias vector b_true:", b_true)
fixed_bias = b_true



Latent probabilities: [0.78455081 0.48455294]
True weight matrix W_true: [[0. 5. 0. 5.]
 [5. 0. 5. 0.]]
True bias vector b_true: [-3 -3 -3 -3]


In [5]:
# ---- Instantiate your sampler ----
sampler = GibbsSamplerLLFM(
    Data=Y,
    K=8,              
    alpha=0.1,
    sigma_w=3.0,
    mu_b=-3.0,
    sigma_b=1,
    n_iter=1000,
    burn=200,
    n_subsample=500
)

# ---- Run MCMC ----
sampler.run()
sampler.get_posterior_samples()


In [6]:
latent_features( Z_post=sampler.good_samples_Z, W_post=sampler.good_samples_W, b_post=sampler.good_samples_b)
p1given0 = sampler.posterior_predictive([1, 0, 0])
print("P(pred=1 | conds=[1,0,0]):", p1given0)

Posterior grouping by number of active features

Number of samples with zero active features: 0/500

Group with 2 active features:
  Number of posterior samples: 46/500
  Average usage probability per feature (size-biased order):
[0.71834783 0.51469565]
  Average weights:
[[-2.12548474  7.74266327 -0.27126942  3.22704498]
 [ 6.8497461  -0.51611186  4.69284434  0.0558465 ]]
  Average Bias:
[-3.10665705 -3.09128296 -2.80056456 -0.90264258]
--------------------------------------------------
Group with 3 active features:
  Number of posterior samples: 337/500
  Average usage probability per feature (size-biased order):
[0.69556083 0.50535905 0.32773294]
  Average weights:
[[ 1.77558407  5.86249691  2.72672206  4.30533568]
 [-1.56437797  2.89111618 -1.35643733  2.50825334]
 [ 4.20893818 -2.05174492  3.24894603 -0.8752644 ]]
  Average Bias:
[-2.40981724 -2.81122885 -2.76388474 -2.03617697]
--------------------------------------------------
Group with 4 active features:
  Number of posterior 

In [ ]:
def write_true_parameters_to_file(
    filename,
    Y,
    Z_true,
    W_true,
    b_true
):
    """
    Writes a structured summary of the true synthetic parameters to file.
    Appends to file so posterior summaries can be added later.
    """

    T, S = Y.shape
    K_true = Z_true.shape[1]

    with open(filename, "a") as f:

        f.write("=" * 60 + "\n")
        f.write("TRUE SYNTHETIC PARAMETERS\n")
        f.write("=" * 60 + "\n\n")

        f.write(f"T (observations): {T}\n")
        f.write(f"S (dimensions):   {S}\n")
        f.write(f"K_true (features): {K_true}\n\n")

        # ---- Latent feature usage ----
        usage = Z_true.sum(axis=0)

        f.write("True latent feature usage counts:\n")
        for k in range(K_true):
            f.write(f"  Feature {k}: active {usage[k]} times\n")
        f.write("\n")

        # ---- True weights ----
        f.write("True weight matrix W_true (K x S):\n")
        f.write(np.array2string(W_true, precision=3))
        f.write("\n\n")

        # ---- True bias ----
        f.write("True bias vector b_true:\n")
        f.write(np.array2string(b_true, precision=3))
        f.write("\n\n")

        # ---- Observed data summary ----
        f.write("Observed data summary (Y):\n")
        f.write(f"  Mean activation per dimension: {Y.mean(axis=0)}\n")
        f.write(f"  Overall mean activation: {Y.mean():.4f}\n\n")

        f.write("=" * 60 + "\n\n")

write_true_parameters_to_file('validation1_overlapping_feature_weight.txt', Y, Z_true, W_true, b_true)

: 

In [ ]:
from evals import latent_features_to_file
latent_features_to_file(filename='validation1_overlapping_feature_weight.txt', Z_post=sampler.good_samples_Z, W_post=sampler.good_samples_W, b_post=sampler.good_samples_b)
p1given0 = sampler.posterior_predictive([1, 0, 0])
print("P(pred=1 | conds=[1,0,0]):", p1given0)

log_numerator: 0.3267140295466753
log_denom: 2.3261272741329133
P(pred=1 | conds=[1,0,0]): 0.13541471524802723


: 

: 